spring:
  h2:
    console:
      enabled: true

  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    show-sql: true
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace